import type { Ruleset } from "../schema";
import { RulesetSchema } from "../schema";

export const genericRuleset: Ruleset = RulesetSchema.parse({
  id: "aoe2-generic-mvp",
  version: "mvp-0.1",
  name: "AoE2 Generic MVP Ruleset",

  startingResources: {
    food: 200,
    wood: 200,
    gold: 100,
    stone: 200,
  },
  startingVillagers: 3,
  startingPopulation: 4,
  startingPopCap: 5,

  gatherRates: {
    sheep: 0.33,
    boar: 0.41,
    berries: 0.31,
    farms: 0.32,
    wood: 0.39,
    gold: 0.38,
    stone: 0.36,
    build: 0,
    walk: 0,
    idle: 0,
  },

  units: {
    villager: {
      id: "villager",
      name: "Villager",
      age: "dark",
      cost: { food: 50 },
      trainedAt: ["town_center"],
      buildTimeSec: 25,
      populationCost: 1,
      tags: ["eco"],
      requirements: [],
    },
    archer: {
      id: "archer",
      name: "Archer",
      age: "feudal",
      cost: { wood: 25, gold: 45 },
      trainedAt: ["archery_range"],
      buildTimeSec: 35,
      populationCost: 1,
      tags: ["military", "ranged"],
      requirements: [],
    },
  },

  buildings: {
    town_center: {
      id: "town_center",
      name: "Town Center",
      age: "dark",
      cost: {},
      buildTimeSec: 0,
      supportsTraining: ["villager"],
      supportsResearch: ["feudal_age", "castle_age"],
      populationProvided: 5,
      requirements: [],
    },
    house: {
      id: "house",
      name: "House",
      age: "dark",
      cost: { wood: 25 },
      buildTimeSec: 25,
      populationProvided: 5,
      requirements: [],
      supportsTraining: [],
      supportsResearch: [],
    },
    mill: {
      id: "mill",
      name: "Mill",
      age: "dark",
      cost: { wood: 100 },
      buildTimeSec: 35,
      populationProvided: 0,
      requirements: [],
      supportsTraining: [],
      supportsResearch: [],
    },
    lumber_camp: {
      id: "lumber_camp",
      name: "Lumber Camp",
      age: "dark",
      cost: { wood: 100 },
      buildTimeSec: 35,
      populationProvided: 0,
      requirements: [],
      supportsTraining: [],
      supportsResearch: [],
    },
    mining_camp: {
      id: "mining_camp",
      name: "Mining Camp",
      age: "dark",
      cost: { wood: 100 },
      buildTimeSec: 35,
      populationProvided: 0,
      requirements: [],
      supportsTraining: [],
      supportsResearch: [],
    },
    barracks: {
      id: "barracks",
      name: "Barracks",
      age: "dark",
      cost: { wood: 175 },
      buildTimeSec: 50,
      populationProvided: 0,
      requirements: [],
      supportsTraining: [],
      supportsResearch: [],
    },
    archery_range: {
      id: "archery_range",
      name: "Archery Range",
      age: "feudal",
      cost: { wood: 175 },
      buildTimeSec: 50,
      populationProvided: 0,
      requirements: [],
      supportsTraining: ["archer"],
      supportsResearch: [],
    },
    blacksmith: {
      id: "blacksmith",
      name: "Blacksmith",
      age: "feudal",
      cost: { wood: 150 },
      buildTimeSec: 40,
      populationProvided: 0,
      requirements: [],
      supportsTraining: [],
      supportsResearch: ["fletching"],
    },
    market: {
      id: "market",
      name: "Market",
      age: "feudal",
      cost: { wood: 175 },
      buildTimeSec: 60,
      populationProvided: 0,
      requirements: [],
      supportsTraining: [],
      supportsResearch: [],
    },
  },

  techs: {
    feudal_age: {
      id: "feudal_age",
      name: "Feudal Age",
      age: "dark",
      researchedAt: "town_center",
      cost: { food: 500 },
      researchTimeSec: 130,
      requirements: [],
      effects: [],
    },
    castle_age: {
      id: "castle_age",
      name: "Castle Age",
      age: "feudal",
      researchedAt: "town_center",
      cost: { food: 800, gold: 200 },
      researchTimeSec: 160,
      requirements: [],
      effects: [],
    },
    fletching: {
      id: "fletching",
      name: "Fletching",
      age: "feudal",
      researchedAt: "blacksmith",
      cost: { food: 100, gold: 50 },
      researchTimeSec: 30,
      requirements: [],
      effects: [],
    },
  },

  civilizations: {
    generic: {
      id: "generic",
      name: "Generic",
      modifiers: [],
      disabledUnits: [],
      disabledBuildings: [],
      disabledTechs: [],
    },
  },

  openings: {
    template_19pop_archers_generic: {
      id: "template_19pop_archers_generic",
      name: "19-pop archers",
      description: "A lightweight opening template used by the MVP scaffold.",
      assumptionsPatch: {},
      events: [
        {
          id: "tmpl_opening_allocations",
          label: "Dark Age villager distribution",
          lane: "eco",
          enabled: true,
          trigger: { type: "on_start" },
          actions: [
            { type: "assign_existing_villagers", count: 3, to: "sheep" },
            { type: "assign_next_villagers", count: 3, to: "sheep" },
            { type: "assign_next_villagers", count: 4, to: "wood" },
            { type: "assign_next_villagers", count: 1, to: "boar" },
            { type: "assign_next_villagers", count: 3, to: "berries" },
            { type: "assign_next_villagers", count: 2, to: "wood" },
            { type: "assign_next_villagers", count: 2, to: "gold" },
            { type: "assign_next_villagers", count: 1, to: "wood" }
          ],
        },
        {
          id: "tmpl_lumber_camp",
          label: "Early Lumber Camp",
          lane: "buildings",
          enabled: true,
          trigger: { type: "at_time", timeSec: 35 },
          actions: [
            { type: "build", buildingId: "lumber_camp", builders: 1, priority: "high" }
          ],
        },
        {
          id: "tmpl_mill",
          label: "Early Mill",
          lane: "buildings",
          enabled: true,
          trigger: { type: "at_time", timeSec: 100 },
          actions: [
            { type: "build", buildingId: "mill", builders: 1, priority: "high" }
          ],
        }
      ],
      policies: [],
    },
  },
});
